### ISSUE TITLE
프로필 컴포넌트 todo

### ISSUE THREAD

**Issue by MIchaeL208099** [onetuks/goguma-library-client#11]
# 프로필 컴포넌트 todo
- [ ] 컴포넌트 추가
  - [x] 고구마 포인트 등급에 따른 이미지 변화하는 컴포넌트 추가
  - [x] 프로필 수정을 누르면 프로필수정 페이지로 가게끔 변화하는 컴포넌트 추가
  - [x] 유저 값에 따라 닉네임과 자기소개가 들어가는 컴포넌트 추가
  - [x] 인스타그램 연결 컴포넌트 추가
  - [x] 유저 값에 따라 서평, 팔로우, 팔로잉 숫자 변경되는(데이터바인딩) 컴포넌트 추가
  - [ ] 기본 프로필, 프로필을 수정하게 되면 기본 프로필에서 설정한 프로필로 변화하는 컴포넌트 추가

# css todo
- [ ] 프로필 옆 윤곽 삭제
- [ ] 멤버 등급에 따른 이미지 컴포넌트 위치 조정
- [ ] 멤버 등급 내역 위치 조정
- [ ] 서평 글자 css 조정
- [ ] 자기소개 css 조정
- [ ] 팔로우 버튼 컴포넌트 크기 조정
- [ ] 인스타그램 버튼 위치 조정

**Comment by onetuks** [comment]
# 작업 사항
- 프로필 이미지 뷰 컴포넌트 구현
- 프로필 통계 뷰 컴포넌트 구현
- 프로필 출석체크(캘린더) 컴포넌트 구현
- 프로필 배지 컴포넌트 구현
