### ISSUE TITLE
남의 서재 페이지 todo

### ISSUE THREAD

**Issue by MIchaeL208099** [onetuks/goguma-library-client#9]
# 수행할 작업
- 프로필 기능
  - [x] 프로필 컴포넌트 이식

- 그래프 기능
   - [x] 작성한 서평 카테고리 갯수에 따른 데이터 연동
   - [x] 디자인 작업

- 작성한 서평 영역
   - [x] 디자인
   - [x] 더보기 칸 누르면 작성한 서평 리스트로 이동
